<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.github.oldmanpushcart</groupId>
    <artifactId>jinx</artifactId>
    <packaging>jar</packaging>
    <version>0.0.1-SNAPSHOT</version>
    <name>jinx</name>
    <url>https://github.com/oldmanpushcart/jinx</url>
    <licenses>
        <license>
            <name>Apache-2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>oldmanpushcart</id>
            <email>oldmanpushcart@gmail.com</email>
            <url>https://github.com/oldmanpushcart</url>
        </developer>
    </developers>
    <scm>
        <url>https://github.com/oldmanpushcart/jinx/tree/master</url>
        <connection>scm:git:ssh://github.com/oldmanpushcart/jinx.git</connection>
        <developerConnection>scm:git:git@github.com:oldmanpushcart/jinx.git</developerConnection>
    </scm>

    <properties>
        <release.jdk.version>17</release.jdk.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <slf4j.version>2.0.17</slf4j.version>
        <logback.version>1.5.29</logback.version>
        <dashscope4j.version>4.0.1-SNAPSHOT</dashscope4j.version>
        <jackson.version>2.21.4</jackson.version>
        <reactor-bom.version>2025.0.5</reactor-bom.version>
        <micronaut.version>4.10.23</micronaut.version>
        <micronaut.validation.version>4.12.0</micronaut.validation.version>

    </properties>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>jinx-meta.properties</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>

                    <!-- 基础编译参数 -->
                    <release>${release.jdk.version}</release>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <showDeprecation>true</showDeprecation>

                    <!-- Micronaut AOT 编译必须的注解处理器 -->
                    <annotationProcessorPaths>
                        <path>
                            <groupId>io.micronaut</groupId>
                            <artifactId>micronaut-inject-java</artifactId>
                            <version>${micronaut.version}</version>
                        </path>
                        <path>
                            <groupId>io.micronaut.validation</groupId>
                            <artifactId>micronaut-validation-processor</artifactId>
                            <version>${micronaut.validation.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <!-- 必须加上这个参数，否则 Micronaut 无法获取方法的参数名 -->
                        <arg>-parameters</arg>
                    </compilerArgs>

                </configuration>
            </plugin>

            <!-- 打包插件 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.2</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>

                            <!--
                            最终打包的文件名
                            -->
                            <finalName>jinx-${project.version}-all</finalName>

                            <!--
                            默认情况下，Shade 插件在打包后会在项目根目录生成一个 dependency-reduced-pom.xml 文件。
                            这个文件会剔除已经被打进 FatJar 里的依赖。
                            -->
                            <createDependencyReducedPom>true</createDependencyReducedPom>

                            <transformers>

                                <!--
                                SPI配置文件合并
                                自动合并所有依赖中 META-INF/services/ 下的同名文件，防止覆盖导致功能缺失
                                -->
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>

                                <!--
                                Apache许可证文件合并
                                 将所有依赖的 LICENSE 文件内容合并，避免版权信息丢失
                                -->
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ApacheLicenseResourceTransformer"/>

                                <!--
                                Apache声明文件合并
                                将所有依赖的 NOTICE 文件内容合并，满足开源协议要求
                                -->
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ApacheNoticeResourceTransformer"/>

                                <!--
                                清单文件合并
                                处理 MANIFEST.MF 文件冲突，并指定程序启动的主类 (Main-Class)
                                -->
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>io.github.oldmanpushcart.jinx.JinxApplication</mainClass>
                                </transformer>

                            </transformers>

                            <!--
                            过滤掉无法合并的资源
                            1. JAR包的数字签名。因为重新打包了，这些签名都会失效，必须让他从fat-jar中去掉，避免触发验证。
                            -->
                            <filters>
                                <filter>
                                    <artifact>*.*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                        <exclude>module-info.class</exclude>
                                    </excludes>
                                </filter>
                            </filters>

                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>

            <!-- JACKSON -->
            <dependency>
                <groupId>com.fasterxml.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>${jackson.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- REACTOR -->
            <dependency>
                <groupId>io.projectreactor</groupId>
                <artifactId>reactor-bom</artifactId>
                <version>${reactor-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <dependencies>

        <!-- Logging -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>${logback.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
        </dependency>

        <!-- DashScope4J -->
        <dependency>
            <groupId>io.github.oldmanpushcart</groupId>
            <artifactId>dashscope4j-agent</artifactId>
            <version>${dashscope4j.version}</version>
        </dependency>

        <!-- Jackson for JSON & YAML -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-parameter-names</artifactId>
        </dependency>

        <!-- Micronaut -->
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-inject</artifactId>
            <version>${micronaut.version}</version>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-http-server-netty</artifactId>
            <version>${micronaut.version}</version>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-json-core</artifactId>
            <version>${micronaut.version}</version>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-jackson-databind</artifactId>
            <version>${micronaut.version}</version>
        </dependency>
        <dependency>
            <groupId>io.micronaut.validation</groupId>
            <artifactId>micronaut-validation</artifactId>
            <version>${micronaut.validation.version}</version>
        </dependency>

        <!-- Project Reactor (Publisher implementation) -->
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.addons</groupId>
            <artifactId>reactor-adapter</artifactId>
        </dependency>


    </dependencies>
</project>
