micronaut:
  application:
    name: jinx
  server:
    charset: UTF-8
    port: 8080
    host: 0.0.0.0

jinx:

  skill:
    directories:
      - ./skills

  mcp:
    version: 1.0.0
    servers:
      amap:
        type: streamable-http
        base-url: https://mcp.amap.com
        endpoint: /mcp?key=${AMAP_MAPS_API_KEY}

  dashscope:
    client:
      ak: ${DASHSCOPE_AK}
      http:
        connect-timeout: 5s
        read-timeout: 60s
        write-timeout: 30s
    agent:
      dataspace: ./data
      workspace: ./
      model: qwen-flash
