micronaut:
  application:
    name: jinx
  server:
    charset: UTF-8
    port: 8080
    host: 0.0.0.0

jinx:
  dataspace: ./data
  workspace: ./

  skill:
    directories:
      - ./skills

  mcp:
    servers:
      amap:
        type: streamable-http
        url: https://mcp.amap.com/mcp?key=${AMAP_MAPS_API_KEY}

  agent:
    model: qwen-flash
    client:
      ak: ${DASHSCOPE_AK}
      http:
        connect-timeout: 5s
        read-timeout: 60s
        write-timeout: 30s