micronaut:
  application:
    name: jinx
  server:
    charset: UTF-8
    port: 8080
    host: 0.0.0.0
  http:
    client:
      connect-timeout: 5s
      read-timeout: 60s
      write-timeout: 30s

jinx:

  skill:
    directories:
      - ./skills

  mcp:
    servers:
      amap:
        type: streamable-http
        base-url: https://mcp.amap.com
        endpoint: /mcp?key=${AMAP_MAPS_API_KEY}

  dashscope:
    client:
      ak: ${DASHSCOPE_AK}
      http:
        connect-timeout: ${micronaut.http.client.connect-timeout}
        read-timeout: ${micronaut.http.client.read-timeout}
        write-timeout: ${micronaut.http.client.write-timeout}
    agent:
      dataspace: ./data
      workspace: ./
      model: qwen-flash
